// GENERATED by Tools/RarityGrader/extract.py from the Core joker/power
// definitions. Do not edit by hand; re-run the extractor to refresh.
window.ITEMS = [
  {
    "cls": "RenovasyonJoker",
    "kind": "joker",
    "defId": "renovasyon",
    "name": "Renovasyon",
    "en": "Twice per round, discard your whole hand and draw a fresh one. Costs no turn; disabled in overtime.",
    "tr": "Raunt başına 2 kez tüm elini ıskartaya atıp yeni el çekersin. Tur harcamaz, uzatmada çalışmaz.",
    "legendary": false,
    "sell": 30
  },
  {
    "cls": "IadeJoker",
    "kind": "joker",
    "defId": "iade",
    "name": "İade",
    "en": "Twice per round, return a single held block and draw a replacement. Costs no turn.",
    "tr": "Raunt başına 2 kez elindeki tek bir bloğu iade edip yenisini çekersin. Tur harcamaz.",
    "legendary": false,
    "sell": 30
  },
  {
    "cls": "InsiderJoker",
    "kind": "joker",
    "defId": "insider",
    "name": "Insider",
    "en": "You see the top card of the draw pile.",
    "tr": "Çekme destesinin en üstündeki kartı görürsün.",
    "legendary": false,
    "sell": 35
  },
  {
    "cls": "CigJoker",
    "kind": "joker",
    "defId": "cig",
    "name": "Çığ",
    "en": "Score bonus for placing a BIGGER block than last turn; grows as the streak lasts.",
    "tr": "Her tur bir öncekinden BÜYÜK blok koyarsan puan bonusu; seri uzadıkça büyür.",
    "legendary": false,
    "sell": 40
  },
  {
    "cls": "DondurmaJoker",
    "kind": "joker",
    "defId": "dondurma",
    "name": "Dondurma",
    "en": "Score bonus for placing a SMALLER block than last turn; grows as the streak lasts.",
    "tr": "Her tur bir öncekinden KÜÇÜK blok koyarsan puan bonusu; seri uzadıkça büyür.",
    "legendary": false,
    "sell": 40
  },
  {
    "cls": "SiyamJoker",
    "kind": "joker",
    "defId": "siyam",
    "name": "Siyam",
    "en": "Score bonus for placing the SAME shape as last turn; grows as the streak lasts.",
    "tr": "Her tur bir öncekiyle AYNI şekli koyarsan puan bonusu; seri uzadıkça büyür.",
    "legendary": false,
    "sell": 45
  },
  {
    "cls": "BereketJoker",
    "kind": "joker",
    "defId": "bereket",
    "name": "Bereket",
    "en": "Whenever a row and a column explode in the same turn, your score gains grow permanently.",
    "tr": "Aynı turda satır ve sütun birlikte patlarsa kazandığın puan kalıcı olarak artar.",
    "legendary": false,
    "sell": 50
  },
  {
    "cls": "HarcamaBonusuJoker",
    "kind": "joker",
    "defId": "harcama_bonusu",
    "name": "Harcama Bonusu",
    "en": "You gain points every time the draw pile runs out.",
    "tr": "Çekme destesi her tükendiğinde puan kazanırsın.",
    "legendary": false,
    "sell": 40
  },
  {
    "cls": "DomuzKumbarasiJoker",
    "kind": "joker",
    "defId": "domuz_kumbarasi",
    "name": "Domuz Kumbarası",
    "en": "Its sell value grows after every round you complete.",
    "tr": "Tamamladığın her raunt sonunda satış değeri artar.",
    "legendary": false,
    "sell": 20
  },
  {
    "cls": "CimriKumbaraJoker",
    "kind": "joker",
    "defId": "cimri_kumbara",
    "name": "Cimri Kumbara",
    "en": "Its sell value grows a little for every turn you hold it.",
    "tr": "Elde tutulduğu her turda satış değeri biraz artar.",
    "legendary": false,
    "sell": 15
  },
  {
    "cls": "AltinKumbaraJoker",
    "kind": "joker",
    "defId": "altin_kumbara",
    "name": "Altın Kumbara",
    "en": "Every turn, every clean sweep and every completed round grows its sell value.",
    "tr": "Her tur, her temizlik ve tamamladığın her raunt satış değerini artırır.",
    "legendary": false,
    "sell": 30
  },
  {
    "cls": "SeriTetikJoker",
    "kind": "joker",
    "defId": "seri_tetik",
    "name": "Seri Tetik",
    "en": "Hand size +2, but at the end of every turn the unused cards are discarded and replaced. Disabled in overtime.",
    "tr": "El boyutu +2, ama her tur sonunda kullanılmayan kartlar ıskartaya gidip yenileri gelir. Uzatmada çalışmaz.",
    "legendary": false,
    "sell": 55
  },
  {
    "cls": "KaziCalismasiJoker",
    "kind": "joker",
    "defId": "kazi_calismasi",
    "name": "Kazı Çalışması",
    "en": "A block that explodes whole in one go on the turn you place it is returned to your bonus hand.",
    "tr": "Koyduğun turda tek seferde tümüyle patlayan blok bonus eline iade edilir.",
    "legendary": false,
    "sell": 50
  },
  {
    "cls": "BuldozerJoker",
    "kind": "joker",
    "defId": "buldozer",
    "name": "Buldozer",
    "en": "Wipes the board every 4 turns. Pays no points and never counts as a clean sweep.",
    "tr": "Her 4 turda bir oyun alanını siler. Puan vermez, temizlik sayılmaz.",
    "legendary": false,
    "sell": 45
  },
  {
    "cls": "RobotSupurgeJoker",
    "kind": "joker",
    "defId": "robot_supurge",
    "name": "Robot Süpürge",
    "en": "Deletes random cubes after every turn. Triggering the sweep itself grows its capacity and sends it on a short rest.",
    "tr": "Her turdan sonra rastgele küp siler. Temizliği kendisi tetiklerse kapasitesi artar ve kısa süre dinlenir.",
    "legendary": false,
    "sell": 55
  },
  {
    "cls": "KayitDefteriJoker",
    "kind": "joker",
    "defId": "kayit_defteri",
    "name": "Kayıt Defteri",
    "en": "Counts exploded cubes; reaching the board's size triggers a clean sweep. While it is held, emptying the board does not count as one.",
    "tr": "Patlatılan küpleri sayar; sayı alan büyüklüğüne ulaşınca temizlik tetikler. Bu joker dururken alanı boşaltmak temizlik sayılmaz.",
    "legendary": false,
    "sell": 60
  },
  {
    "cls": "KentselDonusumJoker",
    "kind": "joker",
    "defId": "kentsel_donusum",
    "name": "Kentsel Dönüşüm",
    "en": "After every completed round the board permanently gains an extra block of space.",
    "tr": "Tamamladığın her raunt sonunda oyun alanına kalıcı olarak bir blokluk ekstra yer açılır.",
    "legendary": false,
    "sell": 70
  },
  {
    "cls": "BatakJoker",
    "kind": "joker",
    "defId": "batak",
    "name": "Batak",
    "en": "Bet that you will sweep the board within a chosen number of turns. Miss it and the round ends; make it and the payout multiplies.",
    "tr": "İstersen 'şu kadar turda temizlerim' diye bahse girersin. Tutturamazsan raunt biter, tutturursan aradaki puanı katlayarak alırsın.",
    "legendary": false,
    "sell": 65
  },
  {
    "cls": "MidasJoker",
    "kind": "joker",
    "defId": "midas",
    "name": "Midas",
    "en": "Holding a gold block in hand (bonus hand included) also earns its bonus, and every gold cube on the board is worth more.",
    "tr": "Altın bloğu elinde tutmak da bonusu için yeterlidir (bonus el dahil), ayrıca tahtadaki her altın küp daha çok puan verir.",
    "legendary": false,
    "sell": 60
  },
  {
    "cls": "ElmasKazmaJoker",
    "kind": "joker",
    "defId": "elmas_kazma",
    "name": "Elmas Kazma",
    "en": "A clean sweep also shatters obsidian, which pays points.",
    "tr": "Temizlik yapınca obsidyenler de patlar ve puan verir.",
    "legendary": false,
    "sell": 55
  },
  {
    "cls": "TutusturJoker",
    "kind": "joker",
    "defId": "tutustur",
    "name": "Tutuştur",
    "en": "When one fire block explodes, ALL fire blocks on the board explode.",
    "tr": "Bir ateş bloğu patlayınca alandaki TÜM ateş blokları patlar.",
    "legendary": false,
    "sell": 60
  },
  {
    "cls": "YanginJoker",
    "kind": "joker",
    "defId": "yangin",
    "name": "Yangın",
    "en": "Once per round: the blocks around fire blocks turn to fire too.",
    "tr": "Raunt başına 1 kez: ateş bloklarının etrafındaki bloklar da ateş olur.",
    "legendary": false,
    "sell": 50
  },
  {
    "cls": "TaskinJoker",
    "kind": "joker",
    "defId": "taskin",
    "name": "Taşkın",
    "en": "Once per round: the blocks around water blocks turn to water too.",
    "tr": "Raunt başına 1 kez: su bloklarının etrafındaki bloklar da su olur.",
    "legendary": false,
    "sell": 50
  },
  {
    "cls": "BuzlukJoker",
    "kind": "joker",
    "defId": "buzluk",
    "name": "Buzluk",
    "en": "Water blocks touching a wall freeze. Ice never blocks a clean sweep and pays extra when exploded.",
    "tr": "Duvara değen su blokları donar. Buz temizliği engellemez ve patlayınca ek puan verir.",
    "legendary": false,
    "sell": 60
  },
  {
    "cls": "SimyaJoker",
    "kind": "joker",
    "defId": "simya",
    "name": "Simya",
    "en": "Elemental blocks in the market arrive with 2 elements at once.",
    "tr": "Marketteki elementli bloklar aynı anda 2 elemente sahip gelir.",
    "legendary": false,
    "sell": 65
  },
  {
    "cls": "DamlayaJoker",
    "kind": "joker",
    "defId": "damlaya",
    "name": "Damlaya Damlaya Göl Olur",
    "en": "Buy nothing at the market and the next round pays a score bonus every turn.",
    "tr": "Marketten bir şey almazsan sonraki raunt her tur puan bonusu alırsın.",
    "legendary": false,
    "sell": 45
  },
  {
    "cls": "IhaleJoker",
    "kind": "joker",
    "defId": "ihale",
    "name": "İhale",
    "en": "At every round start it puts a premium on a random joker's sell price. No new auction opens until that joker is sold.",
    "tr": "Her raunt başında rastgele bir jokere ek satış fiyatı biçer. O joker satılana kadar yeni ihale açılmaz.",
    "legendary": false,
    "sell": 40
  },
  {
    "cls": "KaraDelikJoker",
    "kind": "joker",
    "defId": "kara_delik",
    "name": "Kara Delik",
    "en": "Every clean sweep adds a 1x1 void block to your discard. A void block can be placed on a filled cell and swallows whatever lands on it.",
    "tr": "Her temizlikte ıskartana 1x1 boşluk bloğu ekler. Boşluk bloğu dolu hücreye konabilir ve üstüne geleni yutar.",
    "legendary": false,
    "sell": 70
  },
  {
    "cls": "EnfeksiyonJoker",
    "kind": "joker",
    "defId": "enfeksiyon",
    "name": "Enfeksiyon",
    "en": "Infect one cube. When the same block has sat on it for 3 turns the whole block detonates. The first detonation spreads the infection once into a 3x3 plus - and no further.",
    "tr": "Bir küpü enfekte edersin. Aynı blok o karede 3 tur durursa blok tümüyle patlar. İlk patlama enfeksiyonu bir kez 3x3 artı şeklinde yayar - daha fazla değil.",
    "legendary": false,
    "sell": 60
  },
  {
    "cls": "OryantasyonJoker",
    "kind": "joker",
    "defId": "oryantasyon",
    "name": "Oryantasyon",
    "en": "Played cards are buried at a random depth of the draw pile instead of being discarded. The pile's top card is always visible.",
    "tr": "Kartlar ıskartaya değil, çekme destesinin rastgele bir yerine girer. Destenin en üstteki kartı hep görünür.",
    "legendary": true,
    "sell": 55
  },
  {
    "cls": "DezenformasyonJoker",
    "kind": "joker",
    "defId": "dezenformasyon",
    "name": "Dezenformasyon",
    "en": "After the opening hand is dealt, the draw pile is split into two equal piles - one draw, one discard - kept separate and never mixed. Each turn the two roles swap: you still discard into the current discard and draw from the current draw pile, but which pile is which flips every turn. Hand +1.",
    "tr": "Açılış eli dağıtıldıktan sonra çekme destesi iki eşit, ayrı desteye bölünür - biri çekme biri ıskarta - asla karışmazlar. Her tur roller yer değiştirir: yine mevcut ıskartaya atar, mevcut çekme destesinden çekersin, ama hangi destenin hangisi olduğu her tur değişir. El +1.",
    "legendary": true,
    "sell": 60
  },
  {
    "cls": "ImitasyonJoker",
    "kind": "joker",
    "defId": "imitasyon",
    "name": "İmitasyon",
    "en": "Your hand size equals the discard pile's card count (min 1); leftover hand cards are discarded each turn. Refills draw only what the draw pile holds - it never reshuffles to fill up, and the discard is recycled only when you play into an empty draw pile.",
    "tr": "El boyutun ıskartadaki kart sayısına eşittir (en az 1); tur sonunda elde kalanlar ıskartaya gider. El sadece çekme destesinde olanı çeker - dolmak için karmaz; ıskarta yalnızca boş desteye kart oynadığında geri karılır.",
    "legendary": true,
    "sell": 60
  },
  {
    "cls": "FraksiyonJoker",
    "kind": "joker",
    "defId": "fraksiyon",
    "name": "Fraksiyon",
    "en": "At round start and whenever the draw pile empties, the piles shuffle and split in two; you may then inspect half the discard by clicking it. You may swap the piles once until the next split - after a swap the discard is hidden again.",
    "tr": "Raunt başında ve deste bitince desteler karılıp ikiye bölünür; sonra ıskartaya tıklayarak yarısını inceleyebilirsin. Sonraki bölünmeye kadar desteleri bir kez takas edebilirsin - takastan sonra ıskarta yine gizlenir.",
    "legendary": true,
    "sell": 65
  },
  {
    "cls": "ParazitJoker",
    "kind": "joker",
    "defId": "parazit",
    "name": "Parazit",
    "en": "In the market, attach a joker to a cube of a block in your deck. That joker takes no slot. Its host cube is sweep-exempt and unbreakable by other jokers and powers - only a line you complete destroys it (and the joker).",
    "tr": "Markette bir jokeri destendeki bir bloğun küpüne takarsın. O joker slot işgal etmez. Konak küp temizliğe girmez ve başka joker/güçlerle kırılmaz - sadece senin tamamladığın bir satır onu (ve jokeri) yok eder.",
    "legendary": false,
    "sell": 70
  },
  {
    "cls": "PowerbankJoker",
    "kind": "joker",
    "defId": "powerbank",
    "name": "Powerbank",
    "en": "Once per round, recharges a spent power without waiting for a clean sweep.",
    "tr": "Raunt başına 1 kez, harcanmış bir gücü temizlik beklemeden doldurur.",
    "legendary": false,
    "sell": 55
  },
  {
    "cls": "TutumlulukJoker",
    "kind": "joker",
    "defId": "tutumluluk",
    "name": "Tutumluluk",
    "en": "The fewer cards your deck holds, the more points you score each turn.",
    "tr": "Destendeki kart sayısı ne kadar az ise her tur o kadar fazla puan kazanırsın.",
    "legendary": false,
    "sell": 45
  },
  {
    "cls": "GenelTemizlikJoker",
    "kind": "joker",
    "defId": "genel_temizlik",
    "name": "Genel Temizlik",
    "en": "Clean sweeps triggered by jokers and powers count as sweeps too - normally a joker or power that clears the last block does not count, because it happens between placements.",
    "tr": "Jokerler ve güçler tarafından tetiklenen temizlikler de temizlik sayılır - normalde son bloğu temizleyen bir joker veya güç, blok koymadan önce gerçekleştiği için sayılmaz.",
    "legendary": false,
    "sell": 55
  },
  {
    "cls": "HafizaJoker",
    "kind": "joker",
    "defId": "hafiza",
    "name": "Hafıza",
    "en": "Bonus-hand cards you did not play carry over to the next round. Any beyond your round-start hand size are discarded at random.",
    "tr": "Elinde kalan bonus kartlar sonraki raunda taşınır. Raunt başındaki el büyüklüğünü aşan kartlar rastgele atılır.",
    "legendary": false,
    "sell": 55
  },
  {
    "cls": "CimbizPower",
    "kind": "power",
    "defId": "cimbiz",
    "name": "Cımbız",
    "en": "Rotates a held block of your choice (it does not need to be mechanical).",
    "tr": "Elindeki seçtiğin bloğu çevirir (mekanik blok olması gerekmez).",
    "legendary": false,
    "sell": 35
  },
  {
    "cls": "CaprazlamaPower",
    "kind": "power",
    "defId": "caprazlama",
    "name": "Çaprazlama",
    "en": "Blows up the blocks in a plus-shaped area around a chosen centre.",
    "tr": "Seçtiğin merkezden + şeklinde bir alandaki blokları patlatır.",
    "legendary": false,
    "sell": 35
  },
  {
    "cls": "EkoPower",
    "kind": "power",
    "defId": "eko",
    "name": "Eko",
    "en": "The first use (free) memorises the next explosion; using it again replays it on the same squares. Memory resets every round.",
    "tr": "İlk kullanım (bedava) sonraki patlamayı hafızaya alır, tekrar kullandığında o patlamayı aynı karelerde tekrar eder. Hafıza her raunt sıfırlanır.",
    "legendary": false,
    "sell": 50
  },
  {
    "cls": "CercevePower",
    "kind": "power",
    "defId": "cerceve",
    "name": "Çerçeve",
    "en": "Clears the blocks on the outermost ring of the board.",
    "tr": "Oyun alanının en dış katmanındaki blokları temizler.",
    "legendary": false,
    "sell": 40
  },
  {
    "cls": "KlonPower",
    "kind": "power",
    "defId": "klon",
    "name": "Klon",
    "en": "Adds 2 copies of a held card of your choice to your bonus hand.",
    "tr": "Elindeki seçtiğin kartın 2 kopyasını bonus eline ekler.",
    "legendary": false,
    "sell": 45
  },
  {
    "cls": "BuyutecPower",
    "kind": "power",
    "defId": "buyutec",
    "name": "Büyüteç",
    "en": "Reveals the top two cards of the draw pile.",
    "tr": "Çekme destesinin en üstteki iki kartını açığa çıkarır.",
    "legendary": false,
    "sell": 30
  },
  {
    "cls": "TransferPower",
    "kind": "power",
    "defId": "transfer",
    "name": "Transfer",
    "en": "Swaps the last discarded card with the top of the draw pile; you see what you gave away.",
    "tr": "Iskartadaki son kart ile çekme destesinin üstündeki kart yer değiştirir; verdiğin kartı görürsün.",
    "legendary": false,
    "sell": 35
  },
  {
    "cls": "MayinPower",
    "kind": "power",
    "defId": "mayin",
    "name": "Mayın",
    "en": "Pops a chosen cube. Dropped on an empty cell it arms a mine that detonates the cube that lands on it.",
    "tr": "Seçtiğin küpü patlatır. Boş kareye koyarsan üstüne küp geldiğinde patlar.",
    "legendary": false,
    "sell": 40
  },
  {
    "cls": "HologramPower",
    "kind": "power",
    "defId": "hologram",
    "name": "Hologram",
    "en": "Moves a bonus-hand card into the discard, folding it back into the piles.",
    "tr": "Bonus elindeki bir kartı ıskartaya çıkarıp desteye katar.",
    "legendary": false,
    "sell": 30
  },
  {
    "cls": "HizliCekimSarjoruPower",
    "kind": "power",
    "defId": "hizli_cekim_sarjoru",
    "name": "Hızlı Çekim Şarjörü",
    "en": "Instantly empties the draw pile and forces the discard to reshuffle in.",
    "tr": "Çekme destesini anında bitirir ve ıskartanın karılmasını sağlar.",
    "legendary": false,
    "sell": 45
  },
  {
    "cls": "BardaginBosTarafiPower",
    "kind": "power",
    "defId": "bardagin_bos_tarafi",
    "name": "Bardağın Boş Tarafı",
    "en": "Filled and empty cells on the board swap places (new cubes carry no element). Any row or column the new cubes complete explodes.",
    "tr": "Oyun alanındaki dolu ve boş kareler yer değiştirir (yeni küpler elementsizdir). Yeni küplerin tamamladığı satır veya sütun patlar.",
    "legendary": false,
    "sell": 45
  },
  {
    "cls": "KumSaatiPower",
    "kind": "power",
    "defId": "kum_saati",
    "name": "Kum Saati",
    "en": "Rewinds the board 2 turns. The hand, the piles and the score stay put.",
    "tr": "Oyun alanını 2 tur geriye sarar. El, deste ve ıskarta olduğu gibi kalır.",
    "legendary": false,
    "sell": 60
  },
  {
    "cls": "OltaPower",
    "kind": "power",
    "defId": "olta",
    "name": "Olta",
    "en": "Mark one held card per round; reel it back into your bonus hand. Pulling it from the draw pile is free (the rod stays ready); pulling it from the discard locks the rod until the next clean sweep.",
    "tr": "Raunt başına bir kart işaretlersin; kartı bonus eline çekersin. Çekme destesinden çekmek bedavadır (olta hazır kalır); ıskartadan çekersen olta bir sonraki temizliğe kadar kilitlenir.",
    "legendary": false,
    "sell": 55
  },
  {
    "cls": "TilsimPower",
    "kind": "power",
    "defId": "tilsim",
    "name": "Tılsım",
    "en": "Blows up ghost blocks and turns the space they covered outside the map into play area. Resets when the round ends.",
    "tr": "Hayalet blokları patlatır ve harita dışında kapladıkları yeri oyun alanına katar. Raunt bitince sıfırlanır.",
    "legendary": false,
    "sell": 65
  },
  {
    "cls": "YatayEnflasyonPower",
    "kind": "power",
    "defId": "yatay_enflasyon",
    "name": "Yatay Enflasyon",
    "en": "Widens the board by one column on each side. Lasts 3 turns; when it ends, blocks are pushed back inward.",
    "tr": "Oyun alanının genişliğini sağdan ve soldan birer artırır. 3 tur sürer, bitince bloklar içeri ittirilir.",
    "legendary": false,
    "sell": 55
  },
  {
    "cls": "DikeyEnflasyonPower",
    "kind": "power",
    "defId": "dikey_enflasyon",
    "name": "Dikey Enflasyon",
    "en": "Raises the board by one row at the top and bottom. Lasts 3 turns; when it ends, blocks are pushed back inward.",
    "tr": "Oyun alanının yüksekliğini alttan ve üstten birer artırır. 3 tur sürer, bitince bloklar içeri ittirilir.",
    "legendary": false,
    "sell": 55
  },
  {
    "cls": "HiperEnflasyonPower",
    "kind": "power",
    "defId": "hiper_enflasyon",
    "name": "Hiper Enflasyon",
    "en": "Grows the board by one cell in every direction. Lasts 3 turns; when it ends, blocks are pushed back inward.",
    "tr": "Oyun alanını her yönden birer artırır. 3 tur sürer, bitince bloklar içeri ittirilir.",
    "legendary": false,
    "sell": 70
  },
  {
    "cls": "AsirmaPower",
    "kind": "power",
    "defId": "asirma",
    "name": "Aşırma",
    "en": "Adds 2 copies of a random card from the draw pile to your bonus hand.",
    "tr": "Çekme destesinden rastgele bir kartın 2 kopyasını bonus eline ekler.",
    "legendary": false,
    "sell": 40
  },
  {
    "cls": "YedeklemePower",
    "kind": "power",
    "defId": "yedekleme",
    "name": "Yedekleme",
    "en": "Adds 2 copies of a random card from the discard pile to your bonus hand.",
    "tr": "Iskartadan rastgele bir kartın 2 kopyasını bonus eline ekler.",
    "legendary": false,
    "sell": 40
  },
  {
    "cls": "SogukFuzyonPower",
    "kind": "power",
    "defId": "soguk_fuzyon",
    "name": "Soğuk Füzyon",
    "en": "Copies one card from the discard and one from the draw pile into your bonus hand.",
    "tr": "Iskartadan bir kartın ve çekme elinden bir kartın kopyasını bonus ele koyar.",
    "legendary": false,
    "sell": 45
  },
  {
    "cls": "IkinciSansPower",
    "kind": "power",
    "defId": "ikinci_sans",
    "name": "İkinci Şans",
    "en": "Overtime only, once per round: clears the board (no score, no sweep), pulls your score back to the threshold, reshuffles the deck into the draw pile and plays on.",
    "tr": "Sadece uzatmada, raunt başına bir kez: oyun alanını temizler (puan yok, temizlik sayılmaz), puanını eşiğe çeker, desteyi karıp çekme destesine koyar ve oyun devam eder.",
    "legendary": false,
    "sell": 60
  },
  {
    "cls": "TotemPower",
    "kind": "power",
    "defId": "totem",
    "name": "Totem",
    "en": "Overtime only: pulls your score to the threshold, sends you to the market, and is destroyed.",
    "tr": "Sadece uzatmada: puanını eşiğe çeker, seni market fazına geçirir ve yok olur.",
    "legendary": false,
    "sell": 70
  },
  {
    "cls": "BukulmePower",
    "kind": "power",
    "defId": "bukulme",
    "name": "Bükülme",
    "en": "Mark a held card and copy it to your bonus hand. For the rest of the round, each time the marked card is drawn into your hand another copy is added. A clean sweep lets you re-mark.",
    "tr": "Elindeki bir kartı işaretler ve kopyasını bonus ele koyarsın. O raunt boyunca işaretli kart her ele çekildiğinde bir kopyası daha eklenir. Temizlik yaptığında yeniden işaretleyebilirsin.",
    "legendary": false,
    "sell": 55
  },
  {
    "cls": "HileliZarPower",
    "kind": "power",
    "defId": "hileli_zar",
    "name": "Hileli Zar",
    "en": "In the market, choose the cards that make up your next round's opening hand.",
    "tr": "Market fazında sonraki rauntun başlangıç elini seçebilmeni sağlar.",
    "legendary": false,
    "sell": 55
  }
];
