#!/usr/bin/env python3
# PURPOSE: Regenerate data.js for the rarity grader by reading every joker/power
# definition in Assets/Scripts/Core, in registry order, and pulling out each item's
# DefId, display name, EN/TR description, legendary flag and base sell value.
# Run from anywhere:  python Tools/RarityGrader/extract.py
# It only READS Core source and WRITES Tools/RarityGrader/data.js; nothing else.
import re, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))  # Tools/RarityGrader -> repo root
JOKER_DEFS = os.path.join(ROOT, "Assets", "Scripts", "Core", "Jokers", "Definitions")
POWER_DEFS = os.path.join(ROOT, "Assets", "Scripts", "Core", "Powers", "Definitions")
JOKER_REG = os.path.join(ROOT, "Assets", "Scripts", "Core", "Jokers", "JokerRegistry.cs")
POWER_REG = os.path.join(ROOT, "Assets", "Scripts", "Core", "Powers", "PowerRegistry.cs")
OUT = os.path.join(HERE, "data.js")


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def registry_order(path):
    """Ordered class names as `new XxxJoker()` / `new XxxPower()`."""
    return re.findall(r"new\s+(\w+)\s*\(\)", read(path))


def scan_string_args(text, start):
    """From an index just AFTER a '(', return the top-level comma-separated arguments,
    each the decoded concatenation of its C# string literals. Stops at the matching ')'."""
    i, depth, args, n = start, 1, [""], len(text)
    while i < n:
        c = text[i]
        if c == '"':
            i += 1
            buf = []
            while i < n:
                ch = text[i]
                if ch == "\\":
                    nxt = text[i + 1] if i + 1 < n else ""
                    buf.append({"n": "\n", "t": "\t", '"': '"', "\\": "\\",
                                "r": "\r", "0": "\0"}.get(nxt, nxt))
                    i += 2
                    continue
                if ch == '"':
                    i += 1
                    break
                buf.append(ch)
                i += 1
            args[-1] += "".join(buf)
            continue
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return args
        elif c == "," and depth == 1:
            args.append("")
        i += 1
    return args


def class_segment(txt, name):
    """Source slice for class `name`: from its declaration to the next SIBLING
    (4-space-indented) class, so nested private classes don't cut it short."""
    m = re.search(r"\bclass\s+" + re.escape(name) + r"\b", txt)
    if not m:
        return None
    nxt = re.search(
        r"(?m)^\s{4}(?:public |internal |private |protected |sealed |abstract |static |partial )*class\s+\w+",
        txt[m.end():])
    end = m.end() + nxt.start() if nxt else len(txt)
    return txt[m.start():end]


def find_call(seg, fn):
    m = re.search(re.escape(fn) + r"\s*\(", seg)
    return scan_string_args(seg, m.end()) if m else None


def parse_class(seg):
    base = find_call(seg, "base")
    desc = find_call(seg, "SetDescription")
    sv = re.search(r"BaseSellValue\s*=\s*(\d+)", seg)
    return {
        "defId": (base[0].strip() if base and len(base) > 0 else ""),
        "name": (base[1].strip() if base and len(base) > 1 else ""),
        "en": (desc[0].strip() if desc and len(desc) > 0 else ""),
        "tr": (desc[1].strip() if desc and len(desc) > 1 else ""),
        "legendary": bool(re.search(r"IsLegendary\s*=\s*true", seg)),
        "sell": (int(sv.group(1)) if sv else None),
    }


def collect(def_dir, class_names, kind):
    blob = "\n// ==FILE-BOUNDARY==\n".join(
        read(os.path.join(def_dir, fn)) for fn in sorted(os.listdir(def_dir)) if fn.endswith(".cs"))
    out = []
    for cn in class_names:
        seg = class_segment(blob, cn)
        if seg is None:
            print("!! class not found:", cn, file=sys.stderr)
            continue
        rec = {"cls": cn, "kind": kind}
        rec.update(parse_class(seg))
        out.append(rec)
    return out


def main():
    items = (collect(JOKER_DEFS, registry_order(JOKER_REG), "joker")
             + collect(POWER_DEFS, registry_order(POWER_REG), "power"))
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// GENERATED by Tools/RarityGrader/extract.py from the Core joker/power\n")
        f.write("// definitions. Do not edit by hand; re-run the extractor to refresh.\n")
        f.write("window.ITEMS = ")
        json.dump(items, f, ensure_ascii=False, indent=2)
        f.write(";\n")
    missing = [it["cls"] for it in items if not it["defId"] or not it["en"]]
    print("wrote %d items to %s" % (len(items), OUT), file=sys.stderr)
    if missing:
        print("REVIEW (missing id or EN desc):", ", ".join(missing), file=sys.stderr)


if __name__ == "__main__":
    main()
